# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2024-10"

[[extensions]]
name = "Shipping Protection"
handle = "shipping-protection"
type = "ui_extension"


# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
# network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

[extensions.settings]
[[extensions.settings.fields]]
key = "enable_shipping_protection"
type = "boolean"
name = "Enable Shipping Protection"

[[extensions.settings.fields]]
key = "protection_first_variant"
type = "variant_reference"
name = "Shipping Protection 1st Variant"
description = "Select the variant for cart values under 100"

[[extensions.settings.fields]]
key = "protection_second_variant"
type = "variant_reference"
name = "Shipping Protection 2nd Variant"
description = "Select the variant for cart values above 100"

[[extensions.settings.fields]]
key = "enable_shipping_discount"
type = "boolean"
name = "Enable Shipping Discount"

[[extensions.settings.fields]]
key = "free_shipping_code"
type = "single_line_text_field"
name = "Shipping discount code"

[[extensions.settings.fields]]
key = "enable_mystery_gift"
type = "boolean"
name = "Enable Mystery Gift"

[[extensions.settings.fields]]
key = "mystery_gift_variant"
type = "variant_reference"
name = "Mystery Gift"